// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wgstdlobynkzbxzkckhc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Indnc3RkbG9ieW5remJ4emtja2hjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA4Mzk0NTEsImV4cCI6MjA2NjQxNTQ1MX0._Xl-nvuf88VJDXwycofVVYbl6qCwr0D5flLcOtXl1dI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);